/*
 * Copyright (C) 2013 by Uwe Bonnes (bon@elektron.ikp.physik.tu-darmstadt.de)
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holders nor the names of
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * For additional information see http://www.ethernut.de/
 */

#include <cfg/arch.h>
#include <stdint.h>
#include <dev/hwtimer_stm32.h>
#include <arch/cm3/stm/stm32xxxx.h>
#include <sys/timer.h>
#include <dev/irqreg.h>

#if defined(MCU_STM32F1)
#define TIM1_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM1EN)))
#define TIM2_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM2EN)))
#define TIM3_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM3EN)))
#define TIM4_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM4EN)))
#define TIM5_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM5EN)))
#define TIM6_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM6EN)))
#define TIM7_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM7EN)))
#define TIM8_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM8EN)))
#define TIM9_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM9EN)))
#define TIM10_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM10EN)))
#define TIM11_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM11EN)))
#define TIM12_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM12EN)))
#define TIM13_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM13EN)))
#define TIM14_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM14EN)))

#define TIM1_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM1RST)))
#define TIM2_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM2RST)))
#define TIM3_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM3RST)))
#define TIM4_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM4RST)))
#define TIM5_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM5RST)))
#define TIM6_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM6RST)))
#define TIM7_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM7RST)))
#define TIM8_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM8RST)))
#define TIM9_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM9RST)))
#define TIM10_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM10RST)))
#define TIM11_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM11RST)))
#define TIM12_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM12RST)))
#define TIM13_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM13RST)))
#define TIM14_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM14RST)))

/* TIM 8 only in HD and XL, TIM 9-14 only in XL */
const stm32timer_info timer_info[] = {

    { TIM1_BASE,  0          , &TIM1_CLK_EN,  &TIM1_RESET,  NUT_HWCLK_PCLK2},
    { TIM2_BASE,  &sig_TIM2  , &TIM2_CLK_EN,  &TIM2_RESET,  NUT_HWCLK_PCLK1},
    { TIM3_BASE,  &sig_TIM3  , &TIM3_CLK_EN,  &TIM3_RESET,  NUT_HWCLK_PCLK1},
    { TIM4_BASE,  &sig_TIM4  , &TIM4_CLK_EN,  &TIM4_RESET,  NUT_HWCLK_PCLK1},
    { TIM5_BASE,  &sig_TIM5  , &TIM5_CLK_EN,  &TIM5_RESET,  NUT_HWCLK_PCLK1},
    { TIM6_BASE,  0          , &TIM6_CLK_EN,  &TIM6_RESET,  NUT_HWCLK_PCLK1},
#if defined (STM32F10X_LD) || defined (STM32F10X_LD_VL) ||\
    defined (STM32F10X_MD) || defined (STM32F10X_MD_VL) ||\
    defined (STM32F10X_CL)
    { TIM7_BASE,  &sig_TIM7  , &TIM7_CLK_EN,  &TIM7_RESET,  NUT_HWCLK_PCLK1}
#elif defined (STM32F10X_HD) || defined (STM32F10X_HD_VL)
    { TIM7_BASE,  &sig_TIM7  , &TIM7_CLK_EN,  &TIM7_RESET,  NUT_HWCLK_PCLK1},
    { TIM8_BASE,  0          , &TIM8_CLK_EN,  &TIM8_RESET,  NUT_HWCLK_PCLK2}
#elif defined (STM32F10X_XL)
    { TIM7_BASE,  &sig_TIM7  , &TIM7_CLK_EN,  &TIM7_RESET,  NUT_HWCLK_PCLK1},
    { TIM8_BASE,  0          , &TIM8_CLK_EN,  &TIM8_RESET,  NUT_HWCLK_PCLK2},
    { TIM9_BASE,  0          , &TIM9_CLK_EN,  &TIM9_RESET,  NUT_HWCLK_PCLK2},
    { TIM10_BASE, 0          , &TIM10_CLK_EN, &TIM10_RESET, NUT_HWCLK_PCLK2},
    { TIM11_BASE, 0          , &TIM11_CLK_EN, &TIM11_RESET, NUT_HWCLK_PCLK2},
    { TIM12_BASE, 0          , &TIM12_CLK_EN, &TIM12_RESET, NUT_HWCLK_PCLK1},
    { TIM13_BASE, 0          , &TIM13_CLK_EN, &TIM13_RESET, NUT_HWCLK_PCLK1},
    { TIM14_BASE, 0          , &TIM14_CLK_EN, &TIM14_RESET, NUT_HWCLK_PCLK1}
#else
#warning Unknown STM32F1 subfamily
#endif
};

#elif defined(MCU_STM32L1)

#define TIM2_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM2EN)))
#define TIM3_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM3EN)))
#define TIM4_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM4EN)))
#define TIM6_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM6EN)))
#define TIM7_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM7EN)))
#define TIM9_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM9EN)))
#define TIM10_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM10EN)))
#define TIM11_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM11EN)))

#define TIM2_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM2RST)))
#define TIM3_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM3RST)))
#define TIM4_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM4RST)))
#define TIM6_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM6RST)))
#define TIM7_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM7RST)))
#define TIM9_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM9RST)))
#define TIM10_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM10RST)))
#define TIM11_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM11RST)))

const stm32timer_info timer_info[] = {
    { TIM2_BASE,  &sig_TIM2  , &TIM2_CLK_EN,  &TIM2_RESET,  NUT_HWCLK_PCLK1},
    { TIM3_BASE,  &sig_TIM3  , &TIM3_CLK_EN,  &TIM3_RESET,  NUT_HWCLK_PCLK1},
    { TIM4_BASE,  &sig_TIM4  , &TIM4_CLK_EN,  &TIM4_RESET,  NUT_HWCLK_PCLK1},
    { TIM6_BASE,  0          , &TIM6_CLK_EN,  &TIM6_RESET,  NUT_HWCLK_PCLK1},
    { TIM7_BASE,  &sig_TIM7  , &TIM7_CLK_EN,  &TIM7_RESET,  NUT_HWCLK_PCLK1},
    { TIM9_BASE,  0          , &TIM9_CLK_EN,  &TIM9_RESET,  NUT_HWCLK_PCLK2},
    { TIM10_BASE, 0          , &TIM10_CLK_EN, &TIM10_RESET, NUT_HWCLK_PCLK2},
    { TIM11_BASE, 0          , &TIM11_CLK_EN, &TIM11_RESET, NUT_HWCLK_PCLK2}
};

#elif defined(MCU_STM32F30)

#define TIM1_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM1EN)))
#define TIM2_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM2EN)))
#define TIM3_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM3EN)))
#define TIM4_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM4EN)))
#define TIM6_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM6EN)))
#define TIM7_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM7EN)))
#define TIM8_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM8EN)))
#define TIM15_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM15EN)))
#define TIM16_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM16EN)))
#define TIM17_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM17EN)))

#define TIM1_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM1RST)))
#define TIM2_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM2RST)))
#define TIM3_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM3RST)))
#define TIM4_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM4RST)))
#define TIM6_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM6RST)))
#define TIM7_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM7RST)))
#define TIM8_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM8RST)))
#define TIM15_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM15RST)))
#define TIM16_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM16RST)))
#define TIM17_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM17RST)))

const stm32timer_info timer_info[] = {
    { TIM1_BASE,  0          , &TIM1_CLK_EN,  &TIM1_RESET,  NUT_HWCLK_PCLK2},
    { TIM2_BASE,  &sig_TIM2  , &TIM2_CLK_EN,  &TIM2_RESET,  NUT_HWCLK_PCLK1},
    { TIM3_BASE,  &sig_TIM3  , &TIM3_CLK_EN,  &TIM3_RESET,  NUT_HWCLK_PCLK1},
    { TIM4_BASE,  &sig_TIM4  , &TIM4_CLK_EN,  &TIM4_RESET,  NUT_HWCLK_PCLK1},
    { TIM6_BASE,  &sig_TIM6  , &TIM6_CLK_EN,  &TIM6_RESET,  NUT_HWCLK_PCLK1},
    { TIM7_BASE,  &sig_TIM7  , &TIM7_CLK_EN,  &TIM7_RESET,  NUT_HWCLK_PCLK1},
    { TIM8_BASE,  0          , &TIM8_CLK_EN,  &TIM8_RESET,  NUT_HWCLK_PCLK2},
    { TIM15_BASE, 0          , &TIM15_CLK_EN, &TIM15_RESET, NUT_HWCLK_PCLK2},
    { TIM16_BASE, 0          , &TIM16_CLK_EN, &TIM16_RESET, NUT_HWCLK_PCLK2},
    { TIM17_BASE, 0          , &TIM17_CLK_EN, &TIM17_RESET, NUT_HWCLK_PCLK2},
};

#elif defined(MCU_STM32F2) || defined(MCU_STM32F4)
#define TIM1_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM1EN)))
#define TIM2_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM2EN)))
#define TIM3_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM3EN)))
#define TIM4_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM4EN)))
#define TIM5_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM5EN)))
#define TIM6_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM6EN)))
#define TIM7_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM7EN)))
#define TIM8_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM8EN)))
#define TIM9_CLK_EN  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM9EN)))
#define TIM10_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM10EN)))
#define TIM11_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2ENR,  _BI32(RCC_APB2ENR_TIM11EN)))
#define TIM12_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM12EN)))
#define TIM13_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM13EN)))
#define TIM14_CLK_EN (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1ENR,  _BI32(RCC_APB1ENR_TIM14EN)))

#define TIM1_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM1RST)))
#define TIM2_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM2RST)))
#define TIM3_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM3RST)))
#define TIM4_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM4RST)))
#define TIM5_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM5RST)))
#define TIM6_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM6RST)))
#define TIM7_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM7RST)))
#define TIM8_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM8RST)))
#define TIM9_RESET  (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM9RST)))
#define TIM10_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM10RST)))
#define TIM11_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB2RSTR,  _BI32(RCC_APB2RSTR_TIM11RST)))
#define TIM12_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM12RST)))
#define TIM13_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM13RST)))
#define TIM14_RESET (CM3BBREG(RCC_BASE, RCC_TypeDef, APB1RSTR,  _BI32(RCC_APB1RSTR_TIM14RST)))

const stm32timer_info timer_info[] = {
    { TIM1_BASE,  0          , &TIM1_CLK_EN,  &TIM1_RESET,  NUT_HWCLK_PCLK2},
    { TIM2_BASE,  &sig_TIM2  , &TIM2_CLK_EN,  &TIM2_RESET,  NUT_HWCLK_PCLK1},
    { TIM3_BASE,  &sig_TIM3  , &TIM3_CLK_EN,  &TIM3_RESET,  NUT_HWCLK_PCLK1},
    { TIM4_BASE,  &sig_TIM4  , &TIM4_CLK_EN,  &TIM4_RESET,  NUT_HWCLK_PCLK1},
    { TIM5_BASE,  &sig_TIM5  , &TIM5_CLK_EN,  &TIM5_RESET,  NUT_HWCLK_PCLK1},
    { TIM6_BASE,  0          , &TIM6_CLK_EN,  &TIM6_RESET,  NUT_HWCLK_PCLK1},
    { TIM7_BASE,  &sig_TIM7  , &TIM7_CLK_EN,  &TIM7_RESET,  NUT_HWCLK_PCLK1},
    { TIM8_BASE,  0          , &TIM8_CLK_EN,  &TIM8_RESET,  NUT_HWCLK_PCLK2},
    { TIM9_BASE,  0          , &TIM9_CLK_EN,  &TIM9_RESET,  NUT_HWCLK_PCLK2},
    { TIM10_BASE, 0          , &TIM10_CLK_EN, &TIM10_RESET, NUT_HWCLK_PCLK2},
    { TIM11_BASE, 0          , &TIM11_CLK_EN, &TIM11_RESET, NUT_HWCLK_PCLK2},
    { TIM12_BASE, 0          , &TIM12_CLK_EN, &TIM12_RESET, NUT_HWCLK_PCLK1},
    { TIM13_BASE, 0          , &TIM13_CLK_EN, &TIM13_RESET, NUT_HWCLK_PCLK1},
    { TIM14_BASE, 0          , &TIM14_CLK_EN, &TIM14_RESET, NUT_HWCLK_PCLK1}
};
#endif

int TIM_GetIndex(uint32_t timer)
{
    int i;
    for (i = (sizeof(timer_info)/sizeof(stm32timer_info))-1; i> -1; i--)
        if (timer_info[i].base == timer)
            break;
    return i;
}
